openslide/openslide-bin

.github/workflows/windows.yml
OpenSlide has a mechanism for appending a string to the version.  When building OpenSlide from Git, append the first seven chars of the commit hash.  The Buildbot config used to prepend `g` before the commit hash, but that makes it harder to copy the commit hash, so don't.
=> workflows: include commit ID in OpenSlide version when built from Git

.github/workflows/windows.yml
Now that we have a container image, use it instead of installing packages from scratch every time.  (But `sdist` still needs to install all the dependencies for building OpenSlide, just to get `openslide-tables.c`.)
=> workflows/windows: use `winbuild-builder` container

Dockerfile.builder
We'll need it in a subsequent PR, but this needs to land first so the new container image can be used in CI.
=> Dockerfile.builder: add bzip2

README.md, build.sh
When OpenSlide started using `g_autoptr` in openslide/openslide@50942fe5, MinGW-w64 started linking it with winpthreads for `pthread_once()` and the mutex functions, but only in 32-bit builds.  Apparently none of our other dependencies use GCC cleanup functions, which is why this hasn't shown up earlier.  It's not clear that we can avoid the dependency, and we probably don't want to stop using `g_autoptr`, but libssp showed that it's possible to build and ship our own copies of toolchain libraries.
For consistency, build and ship winpthreads in both 32-bit and 64-bit builds.  Also stop avoiding the pthreads dependency in pixman, which means winpthreads will provide some value on 64-bit platforms as well.
=> Build and ship winpthreads

README.md, build.sh
Reported in https://github.com/openslide/openslide-winbuild/issues/36#issuecomment-1177314723.
=> Fixes for containerized build on Windows

README.md, build.sh
Drop support for non-Fedora distros and for Cygwin, and _only_ support building in the container.  This ensures that everyone uses the build environment we test and ship with, easing maintenance and potentially improving reliability for third-party builds (since cross-compilation can be brittle).
Closes #36.
=> Drop support for building outside container

.github/workflows/windows.yml
After building, invoke the synthetic slide driver in a Windows VM to verify that the library bindings work properly.  This won't work on the current stable release; detect that case and continue anyway.
=> workflows/windows: run smoke test after build

build.sh
On 64-bit Windows, MinGW passes a frame pointer to `_setjmp` so `longjmp` can do a SEH unwind.  This seems to work when the caller is also built with MinGW, but sometimes crashes with `STATUS_BAD_STACK` when the caller is built with MSVC; it appears that this is a longstanding MinGW issue.  In 64-bit builds, override `setjmp()` to pass a `NULL` frame pointer to skip
the SEH unwind.  Our uses of `setjmp`/`longjmp` are all in libpng/libjpeg error handling, which isn't expecting to do any cleanup in intermediate stack frames, so this should be fine.
Fixes https://github.com/openslide/openslide-winbuild/issues/47.
=> Skip `longjmp()` SEH unwind in 64-bit build

.github/workflows/pr.yml
If an openslide-winbuild change introduces new OpenSlide build warnings, we should know about it at the PR stage.
However, don't build the OpenSlide stable release with `-Werror`, since compiler warnings can be added over time and there's nothing we can do about it in existing releases.
=> workflows: have PR CI build OpenSlide main with `-Werror`

Dockerfile.builder
Apparently there was a package dependency change in the latest build and xz dropped out.  Ant was only used for OpenSlide Java, which has switched to Meson.
=> Dockerfile.builder: add xz, drop Ant

Dockerfile.builder
Ant was pulling it in, but we need to be explicit now.
Fixes #67.
=> Dockerfile.builder: re-add `javac`

build.sh
The Cairo Autoconf build has apparently decided that it wants to regenerate `Makefile.in` at build time, which shouldn't be happening.  Automake isn't installed in the container, so the build fails.  Rather than troubleshoot it, switch to the Meson build, since we need to do that anyway.
Cairo has Meson support in-tree, but stable releases have [stalled](https://gitlab.freedesktop.org/cairo/cairo/-/issues/422), so use a development snapshot for now.  We don't update the upregex, so `build.sh updates` will complain that cairo is too new.
=> Update cairo to development snapshot; switch to Meson

build.sh
We don't ship any message catalogs, so gettext isn't providing real localization.  Replace it with the simpler proxy-libintl, built with the default `-DSTUB_ONLY` so it's only a stub.
Current glib unconditionally uses a bundled copy of win-iconv and ignores our external copy.  That leaves libxml2 as the remaining win-iconv user, and libxml2 supports UTF-8, UTF-16, and ISO-8859-1 without using iconv.  Slide formats seem likely to encode their XML as UTF-8 (the default), and the sample slides I checked all do so.  Drop win-iconv to simplify dependencies.
Also disable libtiff docs.
=> Drop win-iconv, replace gettext with proxy-libintl

Dockerfile.builder
The libffi wrap requires Meson 0.64 and Fedora 37 has 0.63.
Revert this when switching to Fedora 38.
=> Dockerfile.builder: install Meson 1.0.0 from PyPI

.github/workflows/windows.yml
rather than from a Git checkout.  This helps ensure that the source zip is complete.
=> workflows: build binary zip from source zip

.github/workflows/windows.yml
In order to ratchet the Meson conversion into OpenSlide, we need to temporarily conditionalize the `autoreconf` run.
=> workflows: conditionalize autoreconf of OpenSlide

.github/workflows/windows.yml, build.sh, meson/cross-win32.ini, meson/cross-win64.ini, meson/include/setjmp.h, meson/meson.build, meson/meson_options.txt, meson/subprojects/openslide-java.wrap, meson/subprojects/openslide.wrap, meson/subprojects/packagefiles/openslide-meson.patch
Backport Meson to OpenSlide 3.4.1 so we can also use it for stable release builds.  Build everything as Meson subprojects and drop support for building packages directly from `build.sh`.
=> Build OpenSlide and OpenSlide Java as Meson subprojects

.github/workflows/release.yml
`action-gh-release` uses the deprecated `set-output` command and appears to be unmaintained.  Use `gh`, which is pre-installed on the runners.
=> workflows: use `gh` command to create releases

meson/subprojects/libdicom.wrap
Use the commit that's pinned in OpenSlide's copy of the wrap.  The libdicom main branch currently has breaking changes in it.
=> Pin libdicom to a commit

.github/workflows/windows.yml, build.sh
Each program costs 1.5 - 2 MB in the binary ZIP.  slidetool implements the functionality of all of them, and can also be used directly as any of the openslide-* programs by copying/renaming the binary.
For https://github.com/openslide/openslide/pull/465.
=> Ship slidetool instead of openslide-* programs if available

meson/subprojects/cairo.wrap
pixman and cairo are now available in wrapdb.  We can't use the pixman one yet because we're still shipping a downstream patch.
=> Replace custom cairo wrap with wrapdb one

build.sh, meson/subprojects/packagecache/CACHEDIR.TAG
The tag is mainly needed when the working directory is a Git checkout, since the package cache can accumulate source tarballs over time.  Commit it directly rather than writing the file at runtime.
We don't copy the tag into the sdist zip.  When the working directory comes from an sdist zip, the `packagecache` files won't change further, and arguably shouldn't be excluded from archiving because they're canonically part of the source tree at that point.
We still don't create `CACHEDIR.TAG` files in the unpacked subproject directories.  Leave that to Meson to implement for now.
=> Commit `packagecache/CACHEDIR.TAG` to repo

Dockerfile.builder
It's in beta, but we want the updated MinGW runtime.
=> Dockerfile.builder: update to Fedora 39

.github/workflows/release.yml, .github/workflows/windows.yml, build.sh
List OpenSlide and OpenSlide Java in bold at the top of the table, since they're the most relevant pieces.  Add the versions of MinGW-w64, GCC, and Binutils in italics at the bottom, since they affect the build but are not directly included in it.
Use the table as the GitHub release description for stable releases, and also include it on the summary page of CI runs.
<details>
<summary>Example output</summary>
| Software             | Version                                               |
| --------             | -------                                               |
| **OpenSlide**        | **3.4.1**                                             |
| **OpenSlide Java**   | **0.12.3**                                            |
| winpthreads          | 11.0.1 …
=> Convert `VERSIONS.txt` to Markdown table; add toolchain versions; use in CI

.github/workflows/container.yml, Dockerfile.builder, README.md, build.sh, builder/Dockerfile, builder/package.accept_keywords, builder/package.use, builder/repos.conf
A Gentoo-based container is significantly larger and takes much longer to build, but gives us more control over the toolchain.  This allows us to do three things:
- Specify the GCC and Binutils versions we want.
- Switch from msvcrt to the UCRT in both 32-bit and 64-bit builds.
- Switch the toolchain from pthreads-based thread intrinsics to win32-based ones so we can drop the winpthreads DLL.
The new builder container doesn't even include winpthreads, so we'll notice if something tries to use it.  A common Meson packaging bug is to introduce an unconditional `threads` dependency in libraries that can use win32 threading primitives directly.
Fixes #48.
=> Switch builder container to Gentoo

build.sh
Gentoo doesn't include the `(GCC)` string we were looking for.
=> Simplify Gentoo GCC version in `VERSIONS.md`

.github/workflows/find-container-digest/action.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/windows.yml
Expect the container repo and image digest as a parameter to the `windows` workflow.  This allows the caller (particularly the nightly builder) to exercise full control over the container image, and ensures that every job in the workflow uses the same image.
Add a `find-container-digest` action that can be invoked from callers' setup jobs to compute the parameter.
This is a breaking change for callers of the `windows` workflow in other repos.
=> workflows: expect builder container repo/digest as parameter

build.sh, meson/cross-win32.ini, meson/cross-win64.ini
Detect if a dependency's static library improperly uses `dllexport`.
=> Check for stray exported symbols in OpenSlide DLL

.github/workflows/update-check.yml, .github/workflows/update-label.yml, build.sh
Automatically check for updates once a week, whenever wraps are updated, or on demand.  Have @openslide-bot maintain a PR with updates from wrapdb, and an issue for any remaining updates reported by `./build.sh updates`.
We need to do this in the context of @openslide-bot, rather than the `GITHUB_TOKEN`, because PRs created by the `GITHUB_TOKEN` can't put their head branch in a fork, and don't automatically run CI.  However, we want to label the issues and PRs, which would require giving @openslide-bot permissions on the repo.  Instead, we have a second, privileged workflow to detect and label these issues/PRs.
Since the workflow maintains the PR branch in @openslide-bot's fork, which may have a stale main branch with different Actions workflows, the bot token must have the `workflow` …
=> workflows: periodically check for updates

.github/workflows/container.yml, .github/workflows/update-check.yml, .github/workflows/update-label.yml
The container rebuild workflow has always lived here, but the scheduled rebuild has historically run from the [openslide/builds](https://github.com/openslide/builds) repo.  The sole reason for this indirection is that openslide/builds has logic to keep the repository active, so GitHub doesn't disable scheduled jobs after 60 days of inactivity.  Now that we have periodic update-checking in this repo, we have that problem here anyway (https://github.com/openslide/openslide-winbuild/issues/144).  Move the timer out of openslide/builds to simplify.
While we're here, clarify the names of the update-checking workflows.
=> workflows: move scheduled container rebuild into this repo

builder/Dockerfile
In practice, `build.sh` now expects to run in the specific container image we ship; we're not going to support other build environments.  Make that explicit by adding a flag file that `build.sh` can check for.  Include a version number, which we can increment if we substantially change the image's functionality in future.
The `build.sh` side will be added in a followup after the image is rebuilt.
=> builder: add flag file noting the identity of the container image

build.sh
The builder container is now ABI versioned.  Assume that the v1 ABI has cross-compilers that use the `win32` thread model.
Also drop the Wine `binfmt_misc` check, which is probably irrelevant now that we're building through Meson.  In any event, the container doesn't have Wine, so attempts to run it via `binfmt_misc` will fail.
=> Replace environment checks with check for builder container

.github/workflows/event-issue.yml, .github/workflows/event-pr.yml, .github/workflows/update-check.yml, .github/workflows/update-label.yml
Detect the closure of a dependency update issue and rerun the update check, since Meson wraps have probably been updated in wrapdb.
Also do some refactoring.
=> workflows: automatically recheck for updates when issue is closed

meson/cross-win32.ini, meson/cross-win64.ini
It's been the default [since GCC 4.7](https://gcc.gnu.org/gcc-4.7/changes.html).
=> Drop redundant `-mms-bitfields` compiler option

meson/cross-win32.ini, meson/cross-win64.ini
GCC &ge; 12 enables `-ftree-vectorize` by default.  binutils &ge; 2.36 enables `--dynamicbase` and `--nxcompat` by default.
=> Drop redundant compiler/linker options

.github/find-container-digest/action.yml, .github/workflows/direct.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml, meson/meson.build, meson/native-linux-amd64.ini
and a temporary GitHub Actions workflow to exercise it.  Allow specifying `windows` or `linux` to the `find-container-images` action.
=> Add native file for Linux build

.github/workflows/direct.yml, build.sh, meson/cross-macos-arm64.ini, meson/cross-macos-x86_64.ini, meson/meson.build, meson/subprojects/gdk-pixbuf.wrap, meson/subprojects/packagefiles/gdk-pixbuf-intl.patch, meson/subprojects/packagefiles/pixman-arm.patch, meson/subprojects/pixman.wrap
Update the Direct workflow to exercise it.  Build for both `x86_64` and `arm64` (as macOS calls them) and merge the builds into universal binaries.  Configure the `slidetool` binary to load `libopenslide.1.dylib` from the same directory.  Create separate debuginfo.
Target macOS 11 and above, since those are the releases that aren't EOL.  Use `ld` export filtering to export only OpenSlide's public symbols; it's safe to configure this globally because the build only produces one dylib.
Compiler hardening flags don't appear to be well-documented on macOS, but `-fstack-protector-strong` appears reasonable.  Use it.
Use zlib, libffi, libxml2, and SQLite from the macOS SDK, rather than shipping our own copies.  macOS also ships PCRE2, but its headers aren't included in the SDK, so don't use it.
=> Add cross files for macOS build

.github/workflows/direct.yml, build.sh, meson/meson.build, meson/meson_options.txt
We always want `buildtype=plain` and `wrap_mode=nofallback`.  Set them in `meson.build` so manual Meson invocations don't need to do it.  Also, add an `openslide_werror` Meson option so `build.sh` or manual Meson builds don't need to know how to pass `werror` options directly to the OpenSlide and OpenSlide Java subprojects.
=> Handle `buildtype`, `wrap_mode`, and OpenSlide `werror` in `meson.build`

.github/ISSUE_TEMPLATE/release.md, .github/workflows/build.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml, README.md, build.sh, meson/include/setjmp.h, meson/meson.build, meson/subprojects/packagecache/CACHEDIR.TAG
Don't rename build artifacts yet.
For https://github.com/openslide/openslide-winbuild/issues/159.
=> Rename repository to `openslide-bin`

.github/ISSUE_TEMPLATE/release.md, build.sh, builder/linux/Dockerfile, builder/windows/Dockerfile
It's possible that we're running in the container, but the ABI version doesn't match.  Make that explicit.
Also note in the Dockerfiles that we shouldn't break container ABI for the most recent stable release.
For https://github.com/openslide/openslide-bin/issues/173.
Also, note in the release checklist that we should possibly announce to forum.image.sc.
=> Clarify error if we don't find the container ABI flag

README.md
Clarify that builds can run from Linux or Windows and that the sample command uses PowerShell and not `cmd.exe` syntax.  Fix syntax error substituting `PWD` variable in PowerShell.
Fixes: https://github.com/openslide/openslide-bin/issues/181
=> README: improve instructions for building from Windows

builder/linux/Dockerfile
Needed for Python wheel support.  auditwheel is Linux-specific, and tomli is already included in the Windows builder container.  Neither is available via dnf.  (tomli is, but not for Python 3.8.)
For: https://github.com/openslide/openslide-bin/issues/160
=> builder/linux: add auditwheel and tomli

.github/workflows/direct.yml, build.sh, deps/meson.build, meson_options.txt
The `openslide-bin` project doesn't directly use `openslide_werror` or `version_suffix`; it just passes them to some subprojects as `default_options`. However, these are _defaults_: they take effect during initial configuration, but if later changed with `meson setup --reconfigure` or `meson configure`, the new values aren't re-propagated to the subprojects. The abstraction thus encourages errors, and it doesn't really add much value in the first place.  Remove the top-level options and replace them with documentation about setting the corresponding subproject options directly.
=> Remove pass-through Meson options

.github/workflows/direct.yml
Have Brew delete and recreate Python symlinks to avoid a conflict with a non-Brew Python installed in the Brew system path.
=> workflows/direct: work around Python packaging bug in macOS runner

.flake8, .pre-commit-config.yaml, machines/cross-win64.ini, pyproject.toml
Move flake8 config to `pyproject.toml`; enable mypy; drop redundant `pkgconfig` setting from win64 machine file.
=> Small config updates

.pre-commit-config.yaml, builder/linux/Dockerfile, pyproject.toml
The Windows builder already has 3.11, and on macOS we can reasonably assume it.  Drop configuration for older Python versions.
=> builder/linux: bump Python to 3.11

.gitattributes, .github/ISSUE_TEMPLATE/release.md, .github/workflows/build.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .gitignore, README.md, artifacts/meson.build, artifacts/postprocess-sdist.py, artifacts/write-bdist.py, build.sh, common/archive.py, common/meson.py, common/software.py, deps/meson.build, machines/cross-macos-arm64.ini, machines/cross-macos-x86_64.ini, machines/cross-windows-x64.ini, machines/native-linux-x86_64.ini, meson.options, utils/get-version.py
Change sdist names to `openslide-bin-<version>.tar.gz` and bdist names to `openslide-bin-<version>-<platform>-<arch>.<ext>` (currently `-windows-x64.zip`).
Change versions to `<openslide-version>.<release>+<suffix>`, e.g. `4.0.0.1+20231207.nightly`, for clarity and for compatibility with [Python package versioning](https://packaging.python.org/en/latest/specifications/version-specifiers/).
Generate bdist archives as a Meson artifact, rather than in `build.sh`, allowing us to avoid the `meson install` step.
Generate sdist archives with `meson dist` rather than building them ourselves.  Switch the archive format to `tar.gz` for compatibility with Python source distributions.  Meson distributes subproject sources as unpacked file trees, so we lose some compression ratio this way, but the …
=> Rework archive names and version numbering; generate archives through Meson

common/archive.py
Directories were being deflated and files were being stored, which is backwards.  Directories should be stored to avoid a couple bytes of compression overhead.  File compression was being overridden by the `compress_type` field in the `ZipInfo` object.  Rather than modifying the object, pass `compress_type` and `compresslevel` to `ZipFile.writestr()`.
Fixes #200.
=> Fix Zip compression

.github/workflows/build.yml, .github/workflows/direct.yml, .github/workflows/release.yml
It's no longer possible for multiple jobs to accumulate results into the same artifact.  Upload separate artifacts for the sdist and bdist archives, and have the release job download both via wildcard.
Unlike OpenSlide Python, which still needs the artifact Zips to have a containing directory name with build information, openslide-bin includes build information in archive names.  Drop the containing directory from the artifact Zips in favor of directly wrapping the enclosed archives.
Continue using job output variables to pass artifact details within the workflow.  However, since there's no longer a single artifact name or directory, workflow-level outputs would need separate variables for each artifact.  Instead, drop the `artifact` output var, and require callers to use wildcards as …
=> workflows: update to artifacts v4

.github/workflows/direct.yml, common/archive.py, common/macos.py, utils/write-universal-bdist.py
Apple clang supports building for multiple architectures at once, e.g. `-arch arm64 -arch x86_64`.  However, some projects make configuration decisions based on the Meson host CPU type, and thus need to build separately for arm64 and x86_64.  We'll handle this by configuring and building twice, and then combining the two bdist artifacts outside of Meson.
Add a tool that walks multiple bdist archives, runs `lipo` to combine Mach-O binaries, adds all architecture-specific relocation files, verifies that all other files are identical between builds, and produces a new tarball.  Filesystem metadata for duplicated items is taken from the first input specified on the command line.
Update the Direct workflow to emit Meson-produced bdist archives, including a universal archive on macOS.  Include …
=> Add tool for combining macOS builds into universal build

build.sh
The SourceForge archive is no longer being updated.
=> Switch libjpeg-turbo upurl to GitHub

.github/workflows/build.yml, .github/workflows/direct.yml
Use the new `save-always` option to save source tarballs even after a CI failure.
=> workflows: update actions/cache to v4

.github/workflows/direct.yml
It's no longer being pulled in by default.  This will no longer be required with glib 2.80.
=> workflows/direct: install setuptools on macOS for glib 2.78

deps/meson.build, subprojects/libopenjp2.wrap, subprojects/libxml2.wrap
The libopenjp2 `build_doc` option was a no-op and was removed in wrapdb.
=> Update libopenjp2, libxml2

.github/workflows/update-check.yml
Use current Python, and remember to notice if `bintool updates` fails.
=> workflows/update-check: fixes for bintool

.github/ISSUE_TEMPLATE/release.md, .github/workflows/build.yml, bintool, common/software.py, deps/meson.build, meson.options, subprojects/packagefiles/zstd-pthread.patch, subprojects/zstd.wrap
Allow specific subprojects to be enabled only when building an overridden OpenSlide (presumably from Git main) but not when building a released OpenSlide.  This allows development dependencies to be added without removing them again for intervening openslide-bin releases.
Use this to enable zstd in dev builds for Zeiss CZI support under development.
cc @iewchen
=> Allow enabling extra deps when overriding OpenSlide; add zstd to dev builds

.github/ISSUE_TEMPLATE/release.md
For https://github.com/openslide/openslide-python/pull/265.
=> templates: OpenSlide Python CI stopped hardcoding `BIN_RELEASE`

bintool
We should drop this workaround once the fix has propagated into all Meson versions we support.
=> Add Meson PR URL for running `git update-index` before `meson dist`

CHANGELOG.md, common/meson.py
Omit the zstd update from the changelog, since it just upstreams a patch we were already carrying.
=> openslide-bin 4.0.0.3

bintool
If we use `platform.machine()` to get the CPU architecture, bintool can build for Linux on any arch as long as a) it's running in a builder container for that arch, and b) a machine file exists.
Don't add any additional containers or machine files for now, since we can't efficiently run non-x86_64 builds in GitHub Actions.
=> bintool: don't hardcode x86_64 for Linux builds

.github/workflows/build.yml
The latter is now an alias for the former.  Switch back so we get future OS updates.
=> workflows: switch from `macos-14` to `macos-latest`

.github/workflows/container-linux.yml, .github/workflows/container-windows.yml
The Windows container rebuild has started failing in CI:
mkfifo: cannot set permissions of '/var/tmp/portage/sys-apps/config-site-0/temp/multijob.YksfGq': Operation not permitted
* ERROR: sys-apps/config-site-0::gentoo failed:
*   (no error message)
This doesn't happen when building locally on Fedora 40.  Updating the CI runner to Ubuntu 24.04 (and thus a newer Podman) fixes it, so do that.
Also rebuild builder containers when their rebuild workflows change.
=> workflows: perform builder container builds on Ubuntu 24.04

builder/linux/Dockerfile, builder/windows/Dockerfile, builder/windows/package.use
Now that there's been an openslide-bin release without OpenSlide Java, drop Java from the builder containers and bump the API versions.
Followup to #241.
=> builder: drop Java

builder/windows/Dockerfile
It's no longer being pulled in as a dependency.
=> builder/windows: explicitly install tomli

builder/linux/Dockerfile, builder/windows/Dockerfile, builder/windows/package.accept_keywords
We're about to remove a bug workaround from `bintool`, and it needs to know that Meson is new enough.
Accept `~amd64` Meson in the Windows builder container so it gets new Meson releases quickly.
=> builder: add new API versions for Meson 1.5.0+

bintool
This is fixed in Meson 1.5.0.  Require Meson 1.5.0 on macOS.  On other platforms, require a builder container that includes it.
=> Drop workaround for sdist failure on stale work tree

.github/workflows/build.yml
The option never actually worked, and is being deprecated upstream.  We could implement it ourselves with separate `actions/cache/save` and `actions/cache/restore` invocations, but don't bother for now.
=> workflows: drop `save-always` from `actions/cache` invocation

deps/meson.build
It carries a performance hit, and upstream recommends disabling it in production builds.  Until now, glib has automatically disabled debug infra with our build settings, but glib 2.82+ will enable it by default.
=> Disable glib debug infrastructure

builder/windows/Dockerfile
When we don't update Meson, there won't be any new distfiles.
Fixes #266.
=> builder/windows: fix container build when latest Meson is stable

artifacts/postprocess-binary.py, bintool, builder/windows/Dockerfile
binutils 2.43 added some columns and a header row to the exported symbol list.  Update our check accordingly.  The new code works with older binutils as well.
We could pin older binutils in the Windows builder container, but that's probably more backward compatibility glue than we want to maintain here.  Bump the builder API version so older openslide-bin source releases will fail cleanly, and have bintool accept both API versions.
=> Fix Windows exported symbol check on binutils 2.43; bump builder API version

.github/workflows/build.yml
Avoid Homebrew deprecation warning:
python-packaging has been deprecated! It will be disabled on 2024-10-05.
=> workflows: install python-packaging from PyPI on macOS

.github/workflows/update-check.yml
Forbid maintainers from modifying automatic PRs, since the next workflow run will overwrite their changes.
=> workflows: update `peter-evans/create-pull-request` to v7

.github/workflows/container-linux.yml
We'll eventually want to build arm64 Linux binaries.  Convert the Linux builder container image into a manifest referencing both amd64 and arm64 images.
Building the Linux builder container doesn't require compiling from source, just downloading and unpacking, so we can cross-build it efficiently on amd64.
=> workflows: add arm64 image to Linux builder container

.github/workflows/build.yml, README.md, machines/native-linux-aarch64.ini
For consistency, pass the CPU architecture to `bdist` workflow jobs for all OSes.
=> Add linux-aarch64 artifacts

.github/workflows/build.yml, artifacts/postprocess-sdist.py, common/software.py, deps/meson.build
Hardcode unused source directories and build system blobs to omit from the source tarball.  This reduces the size of the tarball by a factor of five, the development tarball from 90 MiB to 18 MiB and the stable tarball from 88 MiB to 17 MiB.
=> Drop unused data from sdist tarball

common/software.py, subprojects/zlib-ng.wrap
We need to specify the Anitya ID until zlib-ng lands in WrapDB.
=> Fix zlib-ng update checking

artifacts/python/meson.build, artifacts/python/pyproject.in.toml
`__init__.py` has type hints, but type checkers will ignore these when checking OpenSlide Python unless we add `py.typed`.
Also add Trove classifier, by convention.
=> Mark Python wheel as containing type hints

.github/workflows/build.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/update-check.yml, .pre-commit-config.yaml, artifacts/python/pyproject.in.toml, common/software.py, pyproject.toml
`Path.walk()` is not available in Python 3.11; use `os.walk()` instead.  CI didn't catch this because the sdist is built in the Windows builder, which has a newer Python, rather than the Linux builder, which has 3.11.
=> Version bumps for Python 3.13; fix a Python 3.11 incompatibility

.github/workflows/build.yml
[Drop](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) the paid runner.
=> workflows: switch Linux ARM build to publicly-available runner

.github/workflows/container-linux.yml, .github/workflows/container-windows.yml
It's now an alias for `ubuntu-24.04`, so we can stop hardcoding the OS version.
=> workflows: switch container build runners back to `ubuntu-latest`

meson.format
Notwithstanding the Meson docs, `sort_files` has always defaulted to `true`.
=> meson: drop redundant `sort_files` format option

builder/linux/Dockerfile
Add API v4 so bintool can require the newer Python.
=> builder/linux: bump Python to 3.12

.pre-commit-config.yaml, bintool, common/archive.py, common/software.py, pyproject.toml
All v4 and v5 Windows builder images have 3.12, and we just added a v4 Linux image with 3.12.  For macOS we can reasonably assume 3.12 since it's been out for a while.
=> Bump minimum Python to 3.12

.github/workflows/build.yml, bintool, common/python.py
We now require Python 3.12+ and the stdlib can parse TOML since 3.11.
Declare support for new builder APIs (Windows 6, Linux 5) without tomli so we can drop it after the next openslide-bin release.
=> Drop tomli dependency

common/python.py
Serialized Python core metadata must be parsable by `email.parser` with the `compat32` policy, and that configuration fails to remove the newline from the middle of folded headers.  The LGPLv2 Trove classifier triggers this case, and PyPI now has validation that rejects it as an invalid classifier.
Avoid folding by configuring `Message` to produce unlimited line lengths.
=> Avoid line folding in Python core metadata, fixing PyPI upload failure

artifacts/python/README.md, artifacts/python/__init__.in.py, artifacts/python/pyproject.in.toml
Python 3.8 is EOL.  Ubuntu 20.04 is the last officially-supported distro that uses it, and Ubuntu 20.04 will exit standard security maintenance on May 31.
=> Drop Python wheel support for Python 3.8

bintool
Promote gvdb with `meson wrap promote` instead of manually copying the subproject directory.  Clean gvdb before purging subprojects, not after, to prevent purge from failing if glib's `gvdb.wrap` file is missing.
=> Minor improvements to gvdb promotion

builder/linux/Dockerfile, builder/windows/Dockerfile
openslide-bin 4.0.0.8 stopped requiring tomli.
=> builder: drop tomli, bump to new API versions

.github/workflows/build.yml
Caches are immutable and GitHub continues reusing them indefinitely as long as they're accessed once a week.  As a result, we're redownloading newer upstream sources on every build.  Include a truncated hash of the wrap files in the cache key, creating a new cache (after restoring from an existing one) whenever a wrap is changed.
The cache will accumulate old tarballs over time.  Clear these out once per year by switching to a fresh cache without restoring an old one.
=> workflows: include hash of wrap files in `packagecache` cache key

.github/workflows/build.yml
libjpeg-turbo needs it for SIMD support on x86_64.  It turns out we've never had that enabled.
=> workflows: install nasm on macOS
